name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collection: ^1.17.0
  dio: ^5.1.1
  elementary: ^2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  golden_toolkit: ^0.15.0
  intl: ^0.18.0
  mocktail: ^0.3.0
  provider: ^6.0.5
  spider: ^4.2.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.1
  elementary_test: ^1.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true








